title: XDevs Home Page
email: xdevs.hu@gmail.com
encoding: UTF-8
kramdown:
 input: GFM
 hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

description: >
  xdevs page description placeholder
baseurl: ""
url: "https://xdevs-hu.github.io"
github_username:  xdevs-hu

mail_service_url: http://192.168.1.157:9988

markdown: kramdown
plugins:
  - jekyll-feed
#  - jekyll-lunr-js-search

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
