title: XDevs Home Page
email: xdevs.hu@gmail.com
description: >
  xdevs page description placeholder
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xdevs-hu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#url: http://localhost:4000
twitter_username: jekyllrb
github_username:  jekyll

mail_service_url: http://192.168.1.157:9988

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
#  - jekyll-lunr-js-search

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
